config/routes.rb
require 'resque/server'
require 'resque-history/server'
require 'constraints/admin_constraint'

Rails.application.routes.draw do
  root 'root#index'

  namespace :api, :format => :json do
    get 'emails/volume_overtime', :to => 'emails#volume_overtime'

    get 'dkim/usage', :to => 'dkim#usage'
    get 'dkim/usage_overtime', :to => 'dkim#usage_overtime'

    get 'size/average_sizes', :to => 'size#average_sizes'

    get 'image_to_text/ranges', :to => 'image_to_text#ranges'

    get 'address/from_local', :to => 'address#from_local'

    get 'conditional_comments/feature_version', :to => 'conditional_comments#feature_version'
  end

  resources :emails, {:only => :show}
  resources :sites, {:only => [:new, :create]}
  get 'sites', {:to => redirect({:path => '/sites/new'})}

  delete '/logout' => redirect('/admin/logout'), :as => :logout
  namespace :admin do
    root 'sessions#index'
    get '/login' => redirect('/admin/auth/google_oauth2')
    get '/auth/:provider/callback', :to => 'sessions#create'
    delete '/logout', :to => 'sessions#destroy'
  end
  constraints(AdminConstraint) do
    mount RailsAdmin::Engine => '/admin/rails', :as => :rails_admin
    mount Resque::Server => '/admin/resque', :as => :admin_resque
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/helpers/root_helper.rb
module RootHelper
  #def chart(key)
  #  obj = @charts[key]
  #  return nil if obj.nil?()
#
#    content_tag(:canvas, nil, {:'data-chart' => obj.to_json()})
#  end
end

app/views/root/index.html.erb
<div class="jumbotron">
  <h1><%=t('.header')%></h1>
  <p><%=t('.reports.emails.lead')%></p>
</div>

<h4><a id="dkim" href="dkim"><%=t('.reports.dkim.header')%></a></h4>
<p><%=t('.reports.dkim.intro')%> <a href="<%=t('.reports.dkim.more')%>">More >></a></p>
<div class="well">
  <%=pie_chart(api_dkim_usage_path(:format => :json), {:title => t('.reports.dkim.usage')})%>
  <!--<%=line_chart(api_dkim_usage_overtime_path(:format => :json), {:title => t('.reports.dkim.usage_overtime'), :ytitle => t('.reports.dkim.usage_overtime_y'), :min => 0, :max => 100})%>-->
</div>

<h4><a id="size" href="#size"><%=t('.reports.size.header')%></a></h4>
<p><%=t('.reports.size.intro')%> <a href="<%=t('.reports.size.more')%>">More >></a></p>
<div class="well">
  <%=column_chart(api_size_average_sizes_path(:format => :json), {:title => t('.reports.size.average_sizes'), :ytitle => t('.reports.size.average_sizes_y'), :min => 0})%>
</div>

<h4><a id="image_to_text" href="#image_to_text"><%=t('.reports.image_to_text.header')%></a></h4>
<p><%=t('.reports.image_to_text.intro')%> <a href="<%=t('.reports.image_to_text.more')%>">More >></a></p>
<div class="well">
  <%=column_chart(api_image_to_text_ranges_path(:format => :json), {:title => t('.reports.image_to_text.ranges'), :xtitle => t('.reports.image_to_text.ranges_x'), :ytitle => t('.reports.image_to_text.ranges_y'), :min => 0})%>
</div>

<h4><a id="address" href="#address"><%=t('.reports.address.header')%></a></h4>
<p><%=t('.reports.address.intro')%> <a href="<%=t('.reports.address.more')%>">More >></a></p>
<div class="well">
    <%=pie_chart(api_address_from_local_path(:format => :json), {:title => t('.reports.address.from_local')})%>
</div>

<h4><a id="conditional_comments" href="#conditional_comments"><%=t('.reports.conditional_comments.header')%></a></h4>
<p><%=t('.reports.conditional_comments.intro')%> <a href="<%=t('.reports.conditional_comments.more')%>">More >></a></p>
<div class="well">
  <%=pie_chart(api_conditional_comments_feature_version_path(:format => :json), {:title => t('.reports.conditional_comments.feature_version')})%>
</div>

<h4><a id="volume"><%=t('.reports.emails.volume_overtime')%></a></h4>
<p><%=t('.reports.emails.intro')%></p>
<div class="well"><%=line_chart(api_emails_volume_overtime_path(:format => :json), {:title => t('.reports.emails.volume_overtime'), :ytitle => t('.reports.emails.volume_overtime_y'), :min => 0, :height => '150px'})%></div>