config/routes.rb
require 'resque/server'
require 'resque-history/server'
require 'constraints/admin_constraint'

Rails.application.routes.draw do
  root 'root#index'

  namespace :api, :format => :json do
    get 'emails/volume_overtime', :to => 'emails#volume_overtime'

    get 'dkim/usage', :to => 'dkim#usage'
    get 'dkim/usage_overtime', :to => 'dkim#usage_overtime'

    get 'size/average_sizes', :to => 'size#average_sizes'

    get 'image_to_text/ranges', :to => 'image_to_text#ranges'

    get 'address/from_local', :to => 'address#from_local'

    get 'conditional_comments/feature_version', :to => 'conditional_comments#feature_version'
  end

  resources :emails, {:only => :show}
  resources :sites, {:only => [:new, :create]}
  get 'sites', {:to => redirect({:path => '/sites/new'})}

  delete '/logout' => redirect('/admin/logout'), :as => :logout
  namespace :admin do
    root 'sessions#index'
    get '/login' => redirect('/admin/auth/google_oauth2')
    get '/auth/:provider/callback', :to => 'sessions#create'
    delete '/logout', :to => 'sessions#destroy'
  end
  constraints(AdminConstraint) do
    mount RailsAdmin::Engine => '/admin/rails', :as => :rails_admin
    mount Resque::Server => '/admin/resque', :as => :admin_resque
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  #attr_accessor :site_id, :message

  belongs_to :site, :dependent => :destroy
  has_many :reports, :dependent => :destroy
  has_many :report_decimals, :dependent => :destroy, :class_name => 'ReportDecimal'
  has_many :report_integers, :dependent => :destroy, :class_name => 'ReportInteger'
  has_many :report_strings, :dependent => :destroy, :class_name => 'ReportString'

  validates :site, {:presence => true}
  validate do #TODO Better validation
    begin
      self.mail_message()
    rescue
      errors.add(:message, :format)
    end
  end
  validates :sent_at, {:presence => true}

  composed_of :mail_message, {:class_name => 'Mail::Message', :mapping => %w(message encoded)}

  before_validation do
    self.sent_at ||= self.mail_message.date rescue Time.zone.now
  end
end

app/models/metric.rb
module Metric
  def self.table_name_prefix
    'metric_'
  end
end

app/models/report.rb
class Report < ApplicationRecord
  #attr_accessor :email_id, :metric_id, :metric_type, :key

  belongs_to :email, :dependent => :destroy

  validates :email, {:presence => true}
  validates :key, {:presence => true, :uniqueness => {:scope => :email_id, :case_sensitive => true}}

  #def content(options = {})
  #  options = options.merge({:scope => :reports, :metric => self.metric.value})
  #  I18n.translate(self.key, options)
  #end
end

app/models/report_decimal.rb
class ReportDecimal < Report
  validates :decimal, {:numericality => true}

  def value(); self.decimal; end
  def value=(v); self.decimal = v; end
end

app/models/report_integer.rb
class ReportInteger < Report
  validates :integer, {:numericality => {:only_integer => true}}

  def value(); self.integer; end
  def value=(v); self.integer = v; end
end

app/models/report_string.rb
class ReportString < Report
  validates :string, {:presence => true}

  def value(); self.string; end
  def value=(v); self.string = v; end
end

app/models/site.rb
# frozen_string_literal: true
require 'securerandom'
require 'metainspector'

class Site < ApplicationRecord
  EMAIL_ADDRESS_DOMAIN = 'emailmarketing.report'
  EMAIL_ADDRESS_REGEXP = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i.freeze()

  #attr_accessor :name, :url, :email_address, :verified

  has_many :emails, :dependent => :destroy
  has_many :reports, :through => :emails

  composed_of :address, {
    :class_name => 'Mail::Address',
    :mapping => %w(email_address to_s),
    :allow_nil => false
  }

  validates :name, {:presence => true}
  validates :url, {:presence => true, :uniqueness => true}
  validate do #TODO Better validation
    uri = begin
      URI.parse(self.url)
    rescue URI::InvalidURIError
      errors.add(:url, :format)
    end

    #Ensure we don't have an abnormal URL (e.g. mailto, FTP)
    unless uri.is_a?(URI::HTTP) || uri.is_a?(URI::HTTPS)
      errors.add(:url, :format)
    end
  end
  validates :email_address, {:presence => true, :uniqueness => true}
  validate do #TODO Better validation
    self.email_address.to_s() =~ EMAIL_ADDRESS_REGEXP
  end
  validates :verified, {:inclusion => [true, false]}

  after_initialize do
    self.email_address ||= "#{SecureRandom.hex()}@#{EMAIL_ADDRESS_DOMAIN}"
  end
  before_validation do
    self.name ||= self.class.default_name(self.url)
  end

  class << self
    #
    # Clean the provided URL
    #
    def clean_url(url)
      url = url.to_s()
      url = url.prepend('http://') unless url.match(/^http(s)?:\/\//)
      uri = URI.parse(url)
      uri.path = '/'
      uri.query = nil
      uri.fragment = nil
      uri.normalize!()
      uri.to_s()
    end

    #
    # Generate name from the page title
    #
    def default_name(url)
      title = begin
        MetaInspector.new(url).title
      rescue
        Rails.logger.warn($!)
        nil
      end
      title || url
    end
  end
end

app/controllers/admin.rb
module Admin
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ApplicationController
    include ActionView::Helpers::NumberHelper
    
    abstract!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user()
    session[:current_user]
  end

  def current_user=(user)
    session[:current_user] = user
  end
end

app/controllers/emails_controller.rb
#
# Copied from Rails
# https://github.com/rails/rails/blob/master/railties/lib/rails/mailers_controller.rb
#
class EmailsController < ApplicationController
  include EmailHelper

  def show()
    @email = Email.find(params[:id]).mail_message()

    #cid to inline data URLs
    @email = ActionMailer::InlinePreviewInterceptor.previewing_email(@email)

    if params[:part]
      @part_type = Mime::Type.lookup(params[:part])

      if part = find_part(@email, @part_type)
        response.content_type = @part_type
        render plain: part.respond_to?(:decoded) ? part.decoded : part
      else
        raise AbstractController::ActionNotFound, "Email part '#{@part_type}' not found"
      end
    else
      @part = find_preferred_part(@email, request.format, Mime[:html], Mime[:text])
      @part_type = Mime::Type.lookup(@part.mime_type || request.format)
      render layout: false, formats: %w[html]
    end
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites/new
  def new
    @site = Site.new
  end

  # POST /sites
  def create
    @site = Site.new(site_params)
    @site.url = begin
      Site.clean_url(@site.url)
    rescue
      Rails.logger.warn($!)
    end

    #Check if site exists, if so, load it
    existing_site = Site.where({:url => @site.url}).take()
    @site = existing_site unless existing_site.nil?()

    respond_to do |format|
      if verify_recaptcha({:model => @site}) && @site.save
        format.html
      else
        format.html { render :new }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
  def find_preferred_part(mail_message, *formats) # :doc:
    formats.each do |format|
      if part = mail_message.find_first_mime_type(format)
        return part
      end
    end

    if formats.any? { |f| mail_message.mime_type == f }
      mail_message
    end
  end

  def find_part(mail_message, format) # :doc:
    if part = mail_message.find_first_mime_type(format)
      part
    elsif mail_message.mime_type == format
      mail_message
    end
  end
end

app/helpers/root_helper.rb
module RootHelper
  #def chart(key)
  #  obj = @charts[key]
  #  return nil if obj.nil?()
#
#    content_tag(:canvas, nil, {:'data-chart' => obj.to_json()})
#  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109832716-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-109832716-1');
    </script>

    <title><%=t('.title')%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%=yield :head%>
  </head>

  <body>
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li class="<%='active' if current_page?(root_path())%>"><a href="<%=root_path()%>"><%=t('.navigation.home')%></a></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%=t('.navigation.reports')%> <span class="caret"></span>
              </a>

              <ul class="dropdown-menu">
                <li><a href="<%=root_path({:anchor => 'dkim'})%>"><%=t('.navigation.dkim')%></a></li>
                <li><a href="<%=root_path({:anchor => 'size'})%>"><%=t('.navigation.size')%></a></li>
                <li><a href="<%=root_path({:anchor => 'image_to_text'})%>"><%=t('.navigation.image_to_text')%></a></li>
                <li><a href="<%=root_path({:anchor => 'address'})%>"><%=t('.navigation.address')%></a></li>
                <li><a href="<%=root_path({:anchor => 'conditional_comments'})%>"><%=t('.navigation.conditional_comments')%></a></li>
                <li><a href="<%=root_path({:anchor => 'volume'})%>"><%=t('.navigation.volume')%></a></li>
              </ul>
            </li>

            <li class="<%='active' if current_page?(new_site_path()) || current_page?(sites_path())%>">
              <a href="<%=new_site_path()%>" title="<%=t('.navigation.site')%>"><span class="glyphicon glyphicon-plus"></span> <%=t('.navigation.site')%></a>
            </li>

            <li><a href="mailto:carson@reinke.co"><%=t('.navigation.contact')%></a></li>
          </ul>
        </nav>
        <h3 class="text-muted"><%=t('.header')%></h3>
      </div>

      <%= yield %>
    </div>

    <footer>
      <div class="container">
      <p class="text-center"><%=t('.built_by_html')%></p>
    </div>
    </footer>

    <a href="https://github.com/carsonreinke/emailmarketing.report"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/8b6b8ccc6da3aa5722903da7b58eb5ab1081adee/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f6f72616e67655f6666373630302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_orange_ff7600.png"></a>
  </body>
</html>